# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwInjectSample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swinject', '~> 1.1.2'
  pod 'AFNetworking', '~> 3.1.0'
  target 'SwInjectSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwInjectSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
